'use client';

import React from 'react';
import { Sparkles, CheckCircle2, AlertTriangle, HelpCircle, FileText, Award } from 'lucide-react';

interface AIReviewData {
  predictedScore: number;
  titleReview: string;
  executiveCritique: string;
  suggestedKeywords: string[];
  likelyPeerQuestions: string[];
  clarityAssessment: string;
  strengths: string[];
  weaknesses: string[];
}

interface AIPreReviewPanelProps {
  review: AIReviewData;
  onRevise?: () => void;
  onSubmitFinal?: () => void;
  isSubmitting?: boolean;
}

export const AIPreReviewPanel: React.FC<AIPreReviewPanelProps> = ({
  review,
  onRevise,
  onSubmitFinal,
  isSubmitting = false
}) => {
  return (
    <div className="bg-[#faf9f5] border border-[#cccbc8] rounded-[24px] p-6 space-y-6">
      
      {/* Disclaimer Banner */}
      <div className="bg-[#f5e3c7] border border-[#cccbc8] rounded-2xl p-4 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-[#d97757] shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="flex items-center gap-2 font-sans text-xs font-bold text-[#141413]">
            <span className="bg-[#d97757] text-white px-2 py-0.5 rounded text-[10px] font-extrabold uppercase tracking-wider">
              AI Generated Recommendation
            </span>
            <span>Important Disclaimer</span>
          </div>
          <p className="font-serif text-xs text-[#141413]/90 leading-relaxed">
            This AI Pre-Review assessment is an automated analysis generated by AI language models. <strong>It is NOT peer review</strong> and does not guarantee journal acceptance. Use these recommendations to refine your manuscript prior to formal submission.
          </p>
        </div>
      </div>

      {/* Overall Score Badge */}
      <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-2xl p-5 flex items-center justify-between flex-wrap gap-4">
        <div className="space-y-1">
          <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-[#87867f]">
            Predicted Readiness Index (AI Estimate)
          </h4>
          <p className="font-serif text-2xl font-normal text-[#141413]">
            {review.predictedScore >= 85 ? 'High Publication Potential' : 'Solid Draft — Minor Revisions Recommended'}
          </p>
        </div>

        <div className="flex items-center gap-2 bg-[#faf9f5] border border-[#cccbc8] px-4 py-2.5 rounded-2xl">
          <Award className="w-6 h-6 text-[#d97757]" />
          <div>
            <span className="font-sans text-2xl font-bold text-[#141413]">{review.predictedScore}</span>
            <span className="font-sans text-xs text-[#87867f]"> / 100</span>
          </div>
        </div>
      </div>

      {/* Title & Clarity Review */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-xl p-4 space-y-2">
          <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-[#141413] flex items-center gap-1.5">
            <FileText className="w-4 h-4 text-[#d97757]" />
            Title & Keyword Review
          </h4>
          <p className="font-serif text-sm text-[#141413] leading-relaxed">
            {review.titleReview}
          </p>
        </div>

        <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-xl p-4 space-y-2">
          <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-[#141413] flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-[#d97757]" />
            Clarity & Prose Assessment
          </h4>
          <p className="font-serif text-sm text-[#141413] leading-relaxed">
            {review.clarityAssessment}
          </p>
        </div>
      </div>

      {/* Executive Critique */}
      <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-xl p-4 space-y-2">
        <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-[#141413]">
          Executive Editorial Critique
        </h4>
        <p className="font-serif text-sm text-[#141413] leading-relaxed">
          {review.executiveCritique}
        </p>
      </div>

      {/* Likely Peer Reviewer Questions */}
      <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-xl p-4 space-y-2">
        <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-[#d97757] flex items-center gap-1.5">
          <HelpCircle className="w-4 h-4 text-[#d97757]" />
          Anticipated Peer Reviewer Questions
        </h4>
        <ul className="list-disc list-inside font-serif text-sm text-[#141413] space-y-1.5">
          {review.likelyPeerQuestions.map((q, idx) => (
            <li key={idx} className="leading-snug">{q}</li>
          ))}
        </ul>
      </div>

      {/* Strengths and Areas for Improvement */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-xl p-4 space-y-2">
          <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-emerald-800 flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            Key Strengths
          </h4>
          <ul className="list-disc list-inside font-serif text-xs text-[#141413] space-y-1">
            {review.strengths.map((s, idx) => (
              <li key={idx}>{s}</li>
            ))}
          </ul>
        </div>

        <div className="bg-[#f0eee6] border border-[#cccbc8] rounded-xl p-4 space-y-2">
          <h4 className="font-sans text-xs font-bold uppercase tracking-wider text-amber-800 flex items-center gap-1.5">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
            Suggested Revisions
          </h4>
          <ul className="list-disc list-inside font-serif text-xs text-[#141413] space-y-1">
            {review.weaknesses.map((w, idx) => (
              <li key={idx}>{w}</li>
            ))}
          </ul>
        </div>
      </div>

      {/* Suggested Keywords */}
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-sans text-xs text-[#87867f] font-semibold">Suggested Keywords:</span>
        {review.suggestedKeywords.map((kw) => (
          <span key={kw} className="font-sans text-xs bg-[#e3dacc] text-[#141413] px-2.5 py-0.5 rounded-full">
            #{kw}
          </span>
        ))}
      </div>

      {/* Actions */}
      {(onRevise || onSubmitFinal) && (
        <div className="flex items-center justify-between pt-4 border-t border-[#cccbc8]">
          {onRevise && (
            <button onClick={onRevise} className="btn-outlined-dark text-xs py-2.5 px-5">
              Revise Draft
            </button>
          )}

          {onSubmitFinal && (
            <button
              onClick={onSubmitFinal}
              disabled={isSubmitting}
              className="btn-clay text-xs py-2.5 px-6 flex items-center gap-2"
            >
              <Sparkles className="w-4 h-4" />
              <span>{isSubmitting ? 'Submitting...' : 'Submit to Publication Pipeline'}</span>
            </button>
          )}
        </div>
      )}

    </div>
  );
};
